apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: app
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      name: backend
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: localhost:5000/sample-todo-app-backend:latest
        imagePullPolicy: Always
        command: [ "npm", "run", "start" ]
        envFrom:
        - secretRef:
            name: backend
        ports:
        - containerPort: 3000
          protocol: TCP
      restartPolicy: Always
