apiVersion: batch/v1
kind: Job
metadata:
  name: backend-deploy-job
  namespace: app
spec:
  template:
    spec:
      containers:
      - name: job
        image: localhost:5000/sample-todo-app-backend:latest
        command: [ "npm", "run", "db:migrate" ]
        envFrom:
        - secretRef:
            name: backend
      restartPolicy: Never
  backoffLimit: 1
  ttlSecondsAfterFinished: 60
