x-node-shared: &node-shared
  image: todo-node
  tty: true
  stdin_open: true
  command: npm run dev

services:
  frontend:
    <<: *node-shared
    build:
      context: .
      dockerfile: ci/development/node/Dockerfile
    env_file:
    - ./apps/frontend/.env
    volumes:
    - ./apps/frontend:/app
    - frontend-node-modules:/app/node_modules
    ports:
    - "5173:5173"

  backend:
    <<: *node-shared
    env_file:
    - ./apps/backend/.env
    volumes:
    - ./apps/backend:/app
    - backend-node-modules:/app/node_modules
    ports:
    - "3000:3000"
    depends_on:
    - db

  db:
    image: postgres:17.2-alpine
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
    - db-data:/var/lib/postgresql/data

volumes:
  frontend-node-modules:
    driver: local
  backend-node-modules:
    driver: local
  db-data:
    driver: local
