services:
  frontend:
    image: sample-todo-app-node
    build:
      context: ./apps/frontend
      dockerfile: ../../ci/development/node/Dockerfile
    command: npm run dev
    tty: true
    stdin_open: true
    volumes:
      - ./apps/frontend:/app
      - frontend-node-modules:/app/node_modules
    ports:
      - "5173:5173"
    env_file:
      - ./apps/frontend/.env

  backend:
    image: sample-todo-app-node
    command: npm run dev
    tty: true
    stdin_open: true
    volumes:
      - ./apps/backend:/app
      - backend-node-modules:/app/node_modules
    ports:
      - "3000:3000"
    env_file:
      - ./apps/backend/.env
    depends_on:
      - db

  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_PASSWORD: admin
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
    driver: local
  frontend-node-modules:
    driver: local
  backend-node-modules:
    driver: local
